"""Word document writer tool for generating final BRD."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Pt, RGBColor, Inches

from src.tools.base import BaseTool
from src.models import AgentMessage


class DocxWriterTool(BaseTool):
    """
    Generates Word (.docx) documents from agent markdown outputs.

    Creates professional BRD documents with sections, tables,
    formatting, and token accounting summary.
    """

    @property
    def name(self) -> str:
        """Tool name."""
        return "docx_writer"

    @property
    def description(self) -> str:
        """Tool description."""
        return "Generates Word documents (.docx) from markdown sections and metadata."

    async def execute(self, **kwargs) -> Dict[str, Any]:
        """Execute docx generation."""
        # This is a direct use tool, not called via agent
        pass

    async def generate_brd(
        self,
        agent_messages: List[AgentMessage],
        output_dir: Path,
        token_summary: Optional[Dict[str, Any]] = None,
        title: str = "Business Requirement Document",
    ) -> Path:
        """
        Generate a complete BRD Word document.

        Args:
            agent_messages: List of agent output messages
            output_dir: Directory to save the document
            token_summary: Token usage summary
            title: Document title

        Returns:
            Path to generated document
        """
        # Create document
        doc = Document()

        # Add title
        title_para = doc.add_heading(title, 0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add metadata
        metadata_para = doc.add_paragraph()
        metadata_para.add_run("Generated: ").bold = True
        metadata_para.add_run(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        doc.add_paragraph()  # Blank line

        # Add table of contents
        doc.add_heading("Table of Contents", 1)
        toc_items = [
            "Executive Summary",
            "Drool Analysis",
            "Model Analysis",
            "Outbound Analysis",
            "Transformation Analysis",
            "Inbound Analysis",
            "Token Accounting",
            "Appendix",
        ]
        for item in toc_items:
            doc.add_paragraph(item, style="List Bullet")

        doc.add_page_break()

        # Add executive summary
        doc.add_heading("Executive Summary", 1)
        summary_text = f"""
This document contains a comprehensive Business Requirement Document (BRD)
generated by an automated multi-agent system. The BRD incorporates analysis
from {len(agent_messages)} specialized agents that processed and synthesized
information from the provided corpus.

Generated agents:
{chr(10).join(f"- {msg.agent_id}" for msg in agent_messages)}
        """.strip()
        doc.add_paragraph(summary_text)

        doc.add_page_break()

        # Add sections from each agent
        for msg in agent_messages:
            if msg.agent_type.value == "manager":
                section_title = self._format_agent_title(msg.agent_id)
                doc.add_heading(section_title, 1)

                # Add metadata
                meta_para = doc.add_paragraph()
                meta_para_format = meta_para.paragraph_format
                meta_para_format.left_indent = Inches(0.25)

                if msg.token_account:
                    meta_para.add_run(
                        f"Tokens: {msg.token_account.estimated_tokens} | "
                        f"Cost: ${msg.token_account.cost_estimate:.4f} | "
                    ).italic = True
                    meta_para.add_run(
                        f"Duration: {msg.duration_ms:.0f}ms"
                    ).italic = True

                # Add content
                if msg.markdown_content:
                    self._add_markdown_to_doc(doc, msg.markdown_content)
                else:
                    doc.add_paragraph("[No content generated]", style="List Bullet")

                doc.add_paragraph()  # Spacing

        doc.add_page_break()

        # Add token accounting table
        if token_summary:
            doc.add_heading("Token Accounting & Cost Summary", 1)

            # Summary statistics
            summary_table = doc.add_table(rows=5, cols=2)
            summary_table.style = "Light Grid Accent 1"

            rows = summary_table.rows
            rows[0].cells[0].text = "Metric"
            rows[0].cells[1].text = "Value"

            total_input = token_summary.get("total_input_tokens", 0)
            total_output = token_summary.get("total_output_tokens", 0)
            total_cost = token_summary.get("total_cost_estimate", 0)

            rows[1].cells[0].text = "Total Input Tokens"
            rows[1].cells[1].text = str(total_input)

            rows[2].cells[0].text = "Total Output Tokens"
            rows[2].cells[1].text = str(total_output)

            rows[3].cells[0].text = "Total Tokens"
            rows[3].cells[1].text = str(total_input + total_output)

            rows[4].cells[0].text = "Estimated Total Cost"
            rows[4].cells[1].text = f"${total_cost:.6f}"

            doc.add_paragraph()

            # Per-agent breakdown
            if "accounts" in token_summary and token_summary["accounts"]:
                doc.add_heading("Per-Agent Token Usage", 2)
                agent_table = doc.add_table(
                    rows=1 + len(token_summary["accounts"]), cols=5
                )
                agent_table.style = "Light Grid Accent 1"

                header = agent_table.rows[0]
                header.cells[0].text = "Agent ID"
                header.cells[1].text = "Input Tokens"
                header.cells[2].text = "Output Tokens"
                header.cells[3].text = "Estimated"
                header.cells[4].text = "Cost"

                for idx, account in enumerate(token_summary["accounts"], 1):
                    row = agent_table.rows[idx]
                    row.cells[0].text = account.get("agent_id", "")
                    row.cells[1].text = str(account.get("input_tokens", 0))
                    row.cells[2].text = str(
                        account.get("output_tokens", 0)
                    )
                    row.cells[3].text = str(
                        account.get("estimated_tokens", 0)
                    )
                    row.cells[4].text = f"${account.get('cost_estimate', 0):.6f}"

        doc.add_page_break()

        # Add appendix
        doc.add_heading("Appendix", 1)
        doc.add_paragraph("Document Information")
        appendix_info = f"""
Document Type: Business Requirement Document (BRD)
Generation Method: Multi-Agent Async Pipeline
Generated At: {datetime.now().isoformat()}
Total Agents Used: {len(agent_messages)}
Number of Processed Messages: {len(agent_messages)}
        """.strip()
        doc.add_paragraph(appendix_info, style="Normal")

        # Save document
        output_dir.mkdir(parents=True, exist_ok=True)
        output_file = output_dir / f"BRD_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"

        doc.save(str(output_file))

        return output_file

    def _format_agent_title(self, agent_id: str) -> str:
        """Format agent ID as readable title."""
        # Convert "drool_agent_1" to "Drool Agent"
        parts = agent_id.split("_")
        return " ".join(p.capitalize() for p in parts if p != "agent")

    def _add_markdown_to_doc(self, doc: Document, markdown_content: str) -> None:
        """
        Add markdown content to document with basic formatting.

        This is a simplified markdown-to-docx converter.
        For complex markdown, consider using a library like python-docx-markdown.

        Args:
            doc: Document object
            markdown_content: Markdown text to add
        """
        lines = markdown_content.split("\n")

        for line in lines:
            stripped = line.strip()

            if not stripped:
                doc.add_paragraph()  # Blank line
            elif stripped.startswith("# "):
                doc.add_heading(stripped[2:], 1)
            elif stripped.startswith("## "):
                doc.add_heading(stripped[3:], 2)
            elif stripped.startswith("### "):
                doc.add_heading(stripped[4:], 3)
            elif stripped.startswith("- "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped.startswith("* "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped.startswith("1. ") or (
                len(stripped) > 2 and stripped[0].isdigit() and stripped[1] == "."
            ):
                doc.add_paragraph(stripped, style="List Number")
            elif stripped.startswith("> "):
                # Block quote
                para = doc.add_paragraph(stripped[2:])
                para.paragraph_format.left_indent = Inches(0.5)
            else:
                # Regular paragraph
                doc.add_paragraph(stripped)

    async def save_json_summary(
        self,
        output_dir: Path,
        data: Dict[str, Any],
        filename: str = "execution_summary.json",
    ) -> Path:
        """
        Save execution summary as JSON.

        Args:
            output_dir: Output directory
            data: Data to save
            filename: Output filename

        Returns:
            Path to saved file
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        output_file = output_dir / filename

        with open(output_file, "w") as f:
            json.dump(data, f, indent=2, default=str)

        return output_file
